### PR TITLE
Login and Register Page

### PR DESCRIPTION
**Pull request by koshimagoyal**
Created two pages - Login and Registration using HTML and CSS.

For Issue #15

### CODE REVIEW

**Comment by NitinNair89** [comment]
Hi @koshimagoyal 

Can you please post a screenshot? 🙂

**Comment by koshimagoyal** [comment]
hi @NitinNair89 this is how login page looks
login
and this how registration page looks
register

**Comment by NitinNair89** [comment]
Hi @koshimagoyal 
UI looks neat. I will merge this PR and create a new task with some minor suggestions. Would you be willing to work on it? 🙂

**Comment by koshimagoyal** [comment]
Hi @NitinNair89 
Thanks for merging. 

> Hi @koshimagoyal UI looks neat. I will merge this PR and create a new task with some minor suggestions. Would you be willing to work on it? 🙂

I will check the task then will confirm you.

**Comment by NitinNair89** [comment]
> Hi @NitinNair89 Thanks for merging.
> 
> > Hi @koshimagoyal UI looks neat. I will merge this PR and create a new task with some minor suggestions. Would you be willing to work on it? 🙂
> 
> I will check the task then will confirm you.

@koshimagoyal - check this - https://github.com/NitinNair89/TheHungryRecipesApp/issues/34

**Pull request merged**
