### PR TITLE
Added node service, updated base directory structure to separate front and back ends

### PR DESCRIPTION
**Pull request by 4ist**

### CODE REVIEW

**Comment by 4ist** [comment]
Apparently this PR will break the netlify build; @NitinNair can you help me debug? I don't have access to the netlify build logs

**Comment by NitinNair89** [comment]
Hi @4ist 

The logs say that the `build` command failed. Please see below screenshot.

Screenshot from 2020-10-13 20-04-23

---
LOG:

4:00:07 AM: Build ready to start
4:00:09 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
4:00:09 AM: build-image tag: v3.4.1
4:00:09 AM: buildbot version: c6376102eedf4be6c6e5d685c7141e2eb612d47d
4:00:09 AM: Fetching cached dependencies
4:00:09 AM: Starting to download cache of 306.4MB
4:00:11 AM: Finished downloading cache in 2.189408177s
4:00:11 AM: Starting to extract cache
4:00:22 AM: Finished extracting cache in 10.993947746s
4:00:22 AM: Finished fetching cache in 13.285547152s
4:00:22 AM: Starting to prepare the repo for build
4:00:22 AM: Preparing Git Reference pull/28/head
4:00:24 AM: Starting build script
4:00:24 AM: Installing dependencies
4:00:24 AM: Python version set to 2.7
4:00:24 AM: Started restoring cached node version
4:00:27 AM: Finished restoring cached node version
4:00:28 AM: v10.22.1 is already installed.
4:00:29 AM: Now using node v10.22.1 (npm v6.14.6)
4:00:29 AM: Started restoring cached build plugins
4:00:29 AM: Finished restoring cached build plugins
4:00:29 AM: Attempting ruby version 2.6.2, read from environment
4:00:30 AM: Using ruby version 2.6.2
4:00:30 AM: Using PHP version 5.6
4:00:30 AM: 5.2 is already installed.
4:00:30 AM: Using Swift version 5.2
4:00:30 AM: Started restoring cached go cache
4:00:32 AM: Finished restoring cached go cache
4:00:32 AM: Installing Go version 1.12
4:00:32 AM: unset GOOS;
4:00:32 AM: unset GOARCH;
4:00:32 AM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64';
4:00:32 AM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64/bin:${PATH}";
4:00:32 AM: go version >&2;
4:00:32 AM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.12.linux.amd64.env';
4:00:32 AM: go version go1.12 linux/amd64
4:00:32 AM: Installing missing commands
4:00:32 AM: Verify run directory
4:00:33 AM: ​
4:00:33 AM: ┌─────────────────────────────┐
4:00:33 AM: │        Netlify Build        │
4:00:33 AM: └─────────────────────────────┘
4:00:33 AM: ​
4:00:33 AM: ❯ Version
4:00:33 AM:   @netlify/build 4.8.1
4:00:33 AM: ​
4:00:33 AM: ❯ Flags
4:00:33 AM:   deployId: 5f84d8ef3b2eae00079360ed
4:00:33 AM:   mode: buildbot
4:00:33 AM: ​
4:00:33 AM: ❯ Current directory
4:00:33 AM:   /opt/build/repo
4:00:33 AM: ​
4:00:33 AM: ❯ Config file
4:00:33 AM:   No config file was defined: using default values.
4:00:33 AM: ​
4:00:33 AM: ❯ Context
4:00:33 AM:   deploy-preview
4:00:33 AM: ​
4:00:33 AM: ┌───────────────────────────────────┐
4:00:33 AM: │ 1. Build command from Netlify app │
4:00:33 AM: └───────────────────────────────────┘
4:00:33 AM: ​
4:00:33 AM: $ ng build --prod
4:00:33 AM: bash: ng: command not found
4:00:33 AM: ​
4:00:33 AM: ┌─────────────────────────────┐
4:00:33 AM: │   "build.command" failed    │
4:00:33 AM: └─────────────────────────────┘
4:00:33 AM: ​
4:00:33 AM:   Error message
4:00:33 AM:   Command failed with exit code 127: ng build --prod
4:00:33 AM: ​
4:00:33 AM:   Error location
4:00:33 AM:   In Build command from Netlify app:
4:00:33 AM:   ng build --prod
4:00:33 AM: ​
4:00:33 AM:   Resolved config
4:00:33 AM:   build:
4:00:33 AM:     command: ng build --prod
4:00:33 AM:     commandOrigin: ui
4:00:33 AM:     environment:
4:00:33 AM:       - REVIEW_ID
4:00:33 AM:     publish: /opt/build/repo/dist/TheHungryRecipes
4:00:33 AM: Caching artifacts
4:00:33 AM: Started saving build plugins
4:00:33 AM: Finished saving build plugins
4:00:33 AM: Started saving pip cache
4:00:34 AM: Finished saving pip cache
4:00:34 AM: Started saving emacs cask dependencies
4:00:34 AM: Finished saving emacs cask dependencies
4:00:34 AM: Started saving maven dependencies
4:00:34 AM: Finished saving maven dependencies
4:00:34 AM: Started saving boot dependencies
4:00:34 AM: Finished saving boot dependencies
4:00:34 AM: Started saving go dependencies
4:00:35 AM: Finished saving go dependencies
4:00:35 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:00:35 AM: Failing build: Failed to build site
4:00:35 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
4:00:35 AM: Finished processing build request in 26.573798292s

**Comment by 4ist** [comment]
Hi Nitin,

This is more than likely a result of the netlify build command running in the base of the project instead of the front-end folder.

Our options for this are to either update the netlify configuration to pull down that specific directory instead of the base directory (I can help with this although I can not do it myself) or to revert the directory change and put the backend service inside a folder in the frontend directory (not preferred but we can do it this way)

Please let me know what you want to do so we can make the changes accordingly.

**Comment by NitinNair89** [comment]
Hi @4ist 

Please check my reply on the issue. We will discuss it there. 🙂

**Comment by 4ist** [comment]
Hi Nitin,

I have created a Netlify account and deployed the frontend, viewable here: https://nifty-lamarr-d9bc26.netlify.app/

Note that I pointed the netlify build directory to the frontend folder.

Settings > Build & Deploy > Build Settings

image

If you use these same settings then the netlify build should work for you. If it doesn't, feel free to reach out and I'll help you figure it out.

**Comment by 4ist** [comment]
@NitinNair89 Can you please review? I'd like to finalize this issue so we can move forward on the database implementation

**Comment by NitinNair89** [comment]
Hi @4ist 

Yes, please proceed. I have updated the build settings as per your screenshot.

Shall I merge this PR? How to initiate checks again?

**Review by NitinNair89 — APPROVED** [review]

**Pull request merged**
