### PR TITLE
Testcase for Landing component

### PR DESCRIPTION
**Pull request by koshimagoyal**
For issue #20 
Check availability of page description in landing page

### CODE REVIEW

**Comment by koshimagoyal** [comment]
hi @NitinNair 
which comment need to be reviewed?

**Comment by NitinNair89** [comment]
> hi @NitinNair which comment need to be reviewed?

My comments on your PR

**Comment by koshimagoyal** [comment]
@NitinNair89 you have merged this  PR so can I still make changes in this PR or have to create new one?

**Comment by NitinNair89** [comment]
Hi @koshimagoyal 
Thank you for your contribution! Basic test case implementation looks good 👍🏻

**Comment by koshimagoyal** [comment]
Welcome @NitinNair89 Thanks for merging ☺️

**Pull request merged**
